<?php

return [
    'name' => env('BOOKRESA_NAME', 'BookResa'),

    'locales' => [
        'en',
        'ar',
    ],

    'default_locale' => env('BOOKRESA_DEFAULT_LOCALE', 'en'),

    'fallback_locale' => env('BOOKRESA_FALLBACK_LOCALE', 'en'),

    'themes' => [
        'light',
        'dark',
    ],

    'default_theme' => env('BOOKRESA_DEFAULT_THEME', 'system'),

    'rbac' => [
        'permissions' => [
            'business.view',
            'business.update',
            'services.view',
            'services.create',
            'services.update',
            'services.delete',
            'staff.view',
            'staff.manage',
            'customers.view',
            'customers.create',
            'customers.update',
            'bookings.view',
            'bookings.create',
            'bookings.update',
            'bookings.cancel',
            'bookings.complete',
            'calendar.view',
            'billing.view',
            'subscription.manage',
            'settings.manage',
            'reports.view',
        ],

        'roles' => [
            'owner' => [
                'business.view',
                'business.update',
                'services.view',
                'services.create',
                'services.update',
                'services.delete',
                'staff.view',
                'staff.manage',
                'customers.view',
                'customers.create',
                'customers.update',
                'bookings.view',
                'bookings.create',
                'bookings.update',
                'bookings.cancel',
                'bookings.complete',
                'calendar.view',
                'billing.view',
                'subscription.manage',
                'settings.manage',
                'reports.view',
            ],
            'manager' => [
                'business.view',
                'business.update',
                'services.view',
                'services.create',
                'services.update',
                'services.delete',
                'staff.view',
                'staff.manage',
                'customers.view',
                'customers.create',
                'customers.update',
                'bookings.view',
                'bookings.create',
                'bookings.update',
                'bookings.cancel',
                'bookings.complete',
                'calendar.view',
                'settings.manage',
                'reports.view',
            ],
            'receptionist' => [
                'business.view',
                'customers.view',
                'customers.create',
                'customers.update',
                'bookings.view',
                'bookings.create',
                'bookings.update',
                'bookings.cancel',
                'calendar.view',
            ],
            'staff' => [
                'business.view',
                'bookings.view',
                'bookings.update',
                'bookings.complete',
                'calendar.view',
            ],
        ],
    ],

    'tenant' => [
        'model' => \App\Domain\Tenant\Models\Tenant::class,
        'context' => \App\Domain\Tenant\Services\CurrentTenant::class,
    ],
];
