<?php

return [
    'permissions' => [
        'dashboard.view',
        'workspaces.view',
        'workspaces.create',
        'workspaces.update',
        'workspaces.delete',
        'workspaces.members',
        'workspaces.modules',
        'workspaces.payment_accounts',
        'workspaces.impersonate',
        'customers.view',
        'customers.manage',
        'users.view',
        'users.manage',
        'finance.view',
        'finance.manage',
        'plans.manage',
        'reports.view',
        'support.view',
        'support.manage',
        'settings.manage',
        'audit.view',
        'audit.export',
        'security.manage',
        'health.view',
        'broadcast.manage',
    ],

    'roles' => [
        'super_admin' => [
            'label' => 'Super Admin',
            'permissions' => ['*'],
            'tenant_permissions' => ['*'],
        ],
        'operations_admin' => [
            'label' => 'Operations Admin',
            'permissions' => [
                'dashboard.view',
                'workspaces.view',
                'workspaces.create',
                'workspaces.update',
                'workspaces.members',
                'workspaces.modules',
                'workspaces.payment_accounts',
                'workspaces.impersonate',
                'customers.view',
                'customers.manage',
                'users.view',
                'reports.view',
                'support.view',
                'health.view',
                'audit.view',
                'broadcast.manage',
            ],
            'tenant_permissions' => [
                'business.view',
                'business.update',
                'services.view',
                'services.create',
                'services.update',
                'services.delete',
                'staff.view',
                'staff.manage',
                'customers.view',
                'customers.create',
                'customers.update',
                'bookings.view',
                'bookings.create',
                'bookings.update',
                'bookings.cancel',
                'bookings.complete',
                'calendar.view',
                'reports.view',
                'notifications.view',
            ],
        ],
        'finance_admin' => [
            'label' => 'Finance Admin',
            'permissions' => [
                'dashboard.view',
                'workspaces.view',
                'workspaces.payment_accounts',
                'finance.view',
                'finance.manage',
                'plans.manage',
                'reports.view',
                'audit.view',
                'health.view',
            ],
            'tenant_permissions' => [
                'business.view',
                'billing.view',
                'notifications.view',
            ],
        ],
        'support_admin' => [
            'label' => 'Support Admin',
            'permissions' => [
                'dashboard.view',
                'workspaces.view',
                'workspaces.impersonate',
                'customers.view',
                'users.view',
                'support.view',
                'support.manage',
                'reports.view',
                'audit.view',
                'health.view',
                'broadcast.manage',
            ],
            'tenant_permissions' => [
                'business.view',
                'customers.view',
                'customers.create',
                'customers.update',
                'bookings.view',
                'calendar.view',
                'notifications.view',
            ],
        ],
        'security_admin' => [
            'label' => 'Security Admin',
            'permissions' => [
                'dashboard.view',
                'workspaces.view',
                'users.view',
                'users.manage',
                'security.manage',
                'audit.view',
                'audit.export',
                'health.view',
                'reports.view',
            ],
            'tenant_permissions' => [
                'business.view',
                'customers.view',
                'bookings.view',
                'calendar.view',
                'notifications.view',
            ],
        ],
        'viewer' => [
            'label' => 'Read Only',
            'permissions' => [
                'dashboard.view',
                'workspaces.view',
                'customers.view',
                'users.view',
                'finance.view',
                'reports.view',
                'support.view',
                'audit.view',
                'health.view',
            ],
            'tenant_permissions' => [
                'business.view',
                'services.view',
                'staff.view',
                'customers.view',
                'bookings.view',
                'calendar.view',
                'billing.view',
                'reports.view',
                'notifications.view',
            ],
        ],
    ],

    'route_permissions' => [
        'admin.dashboard' => 'dashboard.view',
        'admin.audit.index' => 'audit.view',
        'admin.security.index' => 'security.manage',
        'admin.businesses.index' => 'workspaces.view',
        'admin.businesses.create' => 'workspaces.create',
        'admin.businesses.store' => 'workspaces.create',
        'admin.businesses.edit' => 'workspaces.update',
        'admin.businesses.update' => 'workspaces.update',
        'admin.businesses.destroy' => 'workspaces.delete',
        'admin.businesses.show' => 'workspaces.view',
        'admin.businesses.members.store' => 'workspaces.members',
        'admin.businesses.members.update' => 'workspaces.members',
        'admin.businesses.members.destroy' => 'workspaces.members',
        'admin.businesses.modules.index' => 'workspaces.modules',
        'admin.businesses.modules.update' => 'workspaces.modules',
        'admin.businesses.payment-account.update' => 'workspaces.payment_accounts',
        'admin.businesses.toggle-status' => 'workspaces.update',
        'admin.businesses.impersonate' => 'workspaces.impersonate',
        'admin.customers.index' => 'customers.view',
        'admin.customers.show' => 'customers.view',
        'admin.customers.vip-toggle' => 'customers.manage',
        'admin.users.index' => 'users.view',
        'admin.users.membership-toggle' => 'users.manage',
        'admin.users.platform-admin-toggle' => 'security.manage',
        'admin.users.platform-admin-access' => 'security.manage',
        'admin.subscriptions.index' => 'finance.view',
        'admin.subscriptions.toggle-status' => 'finance.manage',
        'admin.payments.index' => 'finance.view',
        'admin.payments.show' => 'finance.view',
        'admin.payments.verify' => 'finance.manage',
        'admin.payments.refund' => 'finance.manage',
        'admin.usage.index' => 'finance.view',
        'admin.reports.index' => 'reports.view',
        'admin.support.index' => 'support.view',
        'admin.support.show' => 'support.view',
        'admin.support.update' => 'support.manage',
        'admin.support.reply' => 'support.manage',
        'admin.settings.index' => 'settings.manage',
        'admin.settings.update' => 'settings.manage',
        'admin.plans.index' => 'plans.manage',
        'admin.plans.create' => 'plans.manage',
        'admin.plans.store' => 'plans.manage',
        'admin.plans.edit' => 'plans.manage',
        'admin.plans.update' => 'plans.manage',
        'admin.plans.toggle' => 'plans.manage',
        'admin.health.index' => 'health.view',
        'admin.broadcasts.index' => 'broadcast.manage',
        'admin.broadcasts.store' => 'broadcast.manage',
    ],
];
